{"name": "test_add_caculator_error[10以内]", "status": "passed", "description": "这是假发计算器，测试加法有效各种情况，结果是否正确", "steps": [{"name": "第一步：调用加法的方法", "status": "passed", "start": 1599726569798, "stop": 1599726569798}, {"name": "第二部：断言加法运算结果与预期是否一致", "status": "passed", "start": 1599726569798, "stop": 1599726569798}], "parameters": [{"name": "num1", "value": "1"}, {"name": "num2", "value": "2"}, {"name": "result", "value": "3"}], "start": 1599726569798, "stop": 1599726569798, "uuid": "2f0e4b2d-3738-451b-98df-d7c0a9c948fa", "historyId": "418d2df77228601b9fbb520be974fba0", "testCaseId": "5e3d2d6f942a082c51d923142be5b120", "fullName": "test_pytest_allure#test_add_caculator_error", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "加法的计算器测试"}, {"name": "story", "value": "正确的测试用例"}, {"name": "feature", "value": "www.baidu.com"}, {"name": "suite", "value": "test_pytest_allure"}, {"name": "host", "value": "DESKTOP-TBPR3U9"}, {"name": "thread", "value": "11916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest_allure"}], "links": [{"type": "issue", "url": "www.baidu.com", "name": "曾经的bug"}]}